TranasctionWeather/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

weather/urls.py
from django.urls import path

from .views import IndexView, StoreDBView, KeyView, get_address, get_data, VidView

urlpatterns = [
    path('', KeyView.as_view(), name='keys'),
    path('vid/', VidView.as_view(), name='vid'),
    path('home/', IndexView.as_view(), name='home'),
    path('store/', StoreDBView.as_view(), name='store'),
    path('get_address/', get_address, name='get_address'),
    path('get_data/', get_data, name='get_data'),

]

weather/models.py
# Create your models here.
from django.db import models


class Weather(models.Model):
    address = models.CharField(max_length=255)
    date = models.DateField()
    feels_like = models.IntegerField()

    def __str__(self):
        return f'{self.address} on {self.date}'


class Keys(models.Model):
    name = models.CharField(max_length=255)
    key = models.CharField(max_length=255)

    def __str__(self):
        return self.name

weather/forms.py
from django import forms

from weather.models import Weather, Keys


class AddressForm(forms.Form):
    address = forms.CharField(label='Please Enter your address',
                              widget=forms.TextInput(attrs={'placeholder': 'e.g. 129 Rivonia Road'}))


class WeatherForm(forms.ModelForm):
    class Meta:
        model = Weather
        fields = ('address',)


class KeysForm(forms.ModelForm):
    class Meta:
        model = Keys
        fields = '__all__'

weather/views.py
# Create your views here.
import json
from datetime import datetime

from django.core.serializers import serialize
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import FormView, CreateView, TemplateView

from .forms import AddressForm, WeatherForm, KeysForm
from .models import Weather, Keys
from .utils import weather


# Requirement 1
class IndexView(FormView):
    template_name = 'weather/index.html'
    form_class = AddressForm
    success_url = '/home'


class VidView(TemplateView):
    template_name = 'base2.html'


def get_address(request):
    if request.method == 'POST':
        post_text = request.POST.get('address')
        response_data = weather(post_text)
        response_data['date'] = str(response_data['date'])
        response_data['address'] = post_text
        # pprint(response_data)

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    return HttpResponse(
        json.dumps({"nothing to see": "this isn't happening"}),
        content_type="application/json"
    )
    # Requirement 2


def get_data(request):
    if request.method == 'GET':
        climate = serialize('json', Weather.objects.all())
        return HttpResponse(
            json.dumps(climate),
            content_type="application/json"
        )


class StoreDBView(CreateView):
    template_name = 'weather/create.html'
    form_class = WeatherForm
    success_url = 'home/'

    def form_valid(self, form):
        data = self.request.POST['address']
        if data:
            info = weather(data)
            form.instance.address = data
            form.instance.date = datetime.strptime(info['date'], '%A, %d %B %Y %H:%M')
            form.instance.feels_like = int(info['feels'])
            form.save()
            return redirect('home')


class KeyView(CreateView):
    template_name = 'weather/keys.html'
    form_class = KeysForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(KeyView, self).get_context_data(**kwargs)
        map = Keys.objects.filter(name='Map')
        climate = Keys.objects.filter(name='Weather')
        if map.exists() or climate.exists():
            context['Map'] = map
            context['Weather'] = climate
        return context
    # TODO: Get form validation that only accepts Map and Weather as names
    # TODO: Fix frontend so everyhting looks good
    # TODO: Dynamically add HTML Elements

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transaction Weather</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">
        TransWeather
    </a>
</nav>


{% block content %}

{% endblock content %}


{% block javascript %}

{% endblock javascript %}

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trans Weather</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<header class="v-header container">
    <div class="fullscreen-video-wrap">
        <video src="{% static 'img/weather_vid.mov' %}" autoplay="true" loop="true"></video>
    </div>
    <div class="header-overlay"></div>
    <div class="header-content">
        <h3>Welcome To</h3>
        <h1>Transaction Weather</h1>
        <p>Enter an address below and we will show you your weather forcast for the day</p>
        {#        <a href="#" class="btn">Read More</a>#}
    </div>
</header>
{% block content %}

{% endblock content %}
{#<section class="section section-a">#}
{#    <div class="container">#}
{#        <h1>Section A</h1>#}
{#        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores consequuntur cupiditate distinctio#}
{#            doloribus ducimus enim exercitationem harum, molestiae molestias necessitatibus quo repellat repudiandae#}
{#            rerum sit voluptatum? Eveniet ex expedita explicabo fugit iure minus possimus suscipit ullam. Ad architecto#}
{#            asperiores corporis dolore eligendi iure laboriosam laborum quo rem voluptatibus! Molestias, nostrum.</p>#}
{#    </div>#}
{#</section>#}
{##}
{#<section class="section section-b">#}
{#    <div class="container">#}
{#        <h1>Section B</h1>#}
{#        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores consequuntur cupiditate distinctio#}
{#            doloribus ducimus enim exercitationem harum, molestiae molestias necessitatibus quo repellat repudiandae#}
{#            rerum sit voluptatum? Eveniet ex expedita explicabo fugit iure minus possimus suscipit ullam. Ad architecto#}
{#            asperiores corporis dolore eligendi iure laboriosam laborum quo rem voluptatibus! Molestias, nostrum.</p>#}
{#    </div>#}
{#</section>#}

{% block javascript %}

{% endblock javascript %}

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
</body>
</html>

weather/templates/weather/create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}


{% block content %}
    <div class="col-8 mt-5">
        <div id="alert-box"></div>
        <form id="a-form" class="form-group mt-5 text-center" method="post" action="{% url 'store' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-lg btn-outline-secondary" type="submit">Submit</button>
        </form>
    </div>

{% endblock content %}

weather/templates/weather/index.html
{% load static %}
{% include 'base2.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="section section-a">
        <div class="container">
            <div id="alert-box"></div>
            <form id="a-form" class="form-group mt-5 text-center" method="post" action="{% url 'get_address' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="results"></div>
                <button class="btn btn-lg btn-outline-secondary" type="submit">Submit</button>
            </form>
            <div id="talk" class="card mt-5 text-center">
            </div>
        </div>

        <div class="container">
            <form id="b-form" class="form-group mt-5 text-center" method="post" action="{% url 'store' %}">
                {% csrf_token %}
                {{ form.field.as_hidden }}
                <div id="results2"></div>
                <button class="btn btn-lg btn-outline-secondary" type="submit">Save</button>
            </form>
            <div class="mt-5 text-center">
                <button class="btn btn-lg btn-outline-secondary " type="button" id="s-button">List</button>
                <ul id="talk2"></ul>
            </div>
        </div>
    </section>

{% endblock content %}

<footer>
    <p>Author: Bawo Mgemane<br>
        <a href="mailto:bawo@mahlubandile.co.za">bawo@mahlubandile.co.za</a></p>
</footer>

{% block javascript %}
    <script>
        $('#a-form').on('submit', function (event) {
            event.preventDefault();
            create_post();
        });
        $('#b-form').on('submit', function (event) {
            event.preventDefault();
            save_post();
        });
        $('#s-button').click(function (event) {
            event.preventDefault();
            get_post();
        })


        function create_post() {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $.ajax({
                url: "{% url 'get_address' %}", // the endpoint
                type: "POST", // http method
                data: {address: $('#id_address').val()}, // data sent with the post request
                success: function (json) {
                    {#$('#id_address').val(''); // remove the value from the input#}
                    $("#talk").prepend("<div class='card-body'><h5 class='card-title'>" + json.addr + "</h5><h6 class='card-subtitle mb-2 text-muted'>On " + json.date + "</h6><h3 class='card-text'>" + json.feels
                        + "&#8451;</h3></div>"
                    )
                    ;
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " + errmsg +
                        " <a href='home/' class='close'>&times;</a></div>"); // add the error to the dom
                }
            });
        };

        function save_post() {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            $.ajax({
                url: "{% url 'store' %}", // the endpoint
                type: "POST", // http method
                data: {
                    address: $('#id_address').val(),

                }, // data sent with the post request
                success: function (json) {
                    $('#id_address').val(''); // remove the value from the input
                    $('#results2').html("<div class='alert alert-success'>Success " +
                        " <a href='#' class='close'>&times;</a></div>");
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    $('#results2').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " + errmsg +
                        " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                }
            });
        };

        function get_post() {
            $.ajax({
                url: "{% url 'get_data' %}",
                type: "GET",
                success: function (json) {
                    $('#talk2').prepend('<p>' + json + '</p>');
                },
                error: function () {
                    alert("error");
                }
            });
        };
    </script>
{% endblock javascript %}

weather/templates/weather/keys.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-8 mt-5">
        <h3 class="text-center">
            Welcome to the TransWeather App.
        </h3>
    </div>
    <p>Please enter the two api Key's for Open Weather and Map Box</p>

    <div class="col-8 mt-5">
        <form class="form-group mt-5 text-center" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-lg btn-outline-secondary" type="submit">Submit</button>
        </form>
    </div>

    {% if Map and Weather %}
        <a href="{% url 'home' %}" class="btn btn-primary btn-lg btn-block">Go To Main App</a>

    {% else %}
        {% if Map %}
            <p>Please enter the Open Weather API Key to continue</p>
        {% elif Weather %}
            <p>Please enter the MapBox API Key to continue</p>
        {% else %}
            <p>Please enter the Open Weather and MapBox API Key to continue</p>
        {% endif %}

    {% endif %}

{% endblock %}

weather/templates/weather/list.html
{% extends 'base.html' %}

{% block content %}

    {% for q in query %}

        <p>{{ q.date }}</p>
        <p>{{ q.address }}</p>
        <p>{{ q.feels_like }}</p>

    {% endfor %}

{% endblock content %}